### ISSUE TITLE
Improve and expand test coverage

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-ui-kit#715]
**Describe what you want implemented**
I want to increase the number of tests that we run on the components.  I want to see property values changing and testing for the correct output.  Testing for visual differences can also be explored with Chromatic (or alternative, if deemed more suitable).

**Describe "Why" this is needed**
We need to have a high degree of confidence in our UI Kit components and adding more tests improves our confidence.

**Comment by deuch13** [comment]
Currently the only components that haven't had their tests improved are the Table and Wizard.

**Atoms**

- [x] address  
- [x] balance  
- [x] chip  
- [x] date-text  
- [x] drop-down  
- [x] gauge  - cannot be properly tested until issue with d3 library is fixed
- [x] icon  
- [x] loading-indicator  
- [x] logo  
- [x] progress-bar  
- [x] qr-code  
- [x] rich-text  
- [x] skeleton-loader  
- [x] slider  
- [x] text-field  
- [x] toggle  
- [x] truncate-text


**Molecules**

- [x] alert  
- [x] breadcrumb  
- [x] button  
- [x] chart  - cannot be properly tested until issue with d3 library is fixed
- [x] content  
- [x] control  
- [x] cta-list  
- [x] detail-list  
- [x] disclaimer-list  
- [x] file-upload  
- [x] group  
- [x] heading  
- [x] media-content  
- [x] menu  
- [x] mnemonic  
- [x] pagination  
- [x] password-strength  
- [x] statistic  
- [x] step-list


**Organisms**

- [x] accordion  
- [x] card  
- [x] cookie-banner  - cannot be tested because of error from DrakMode component
- [x] error-block  
- [x] footer  
- [x] form  
- [x] hero  
- [x] message-banner  
- [x] navbar  
- [x] search-list  
- [] table  
- [] wizard
